### ISSUE TITLE
SDK Proxy Requires non-default file permissions

### ISSUE THREAD

**Issue by dakotawashok** [DevCycleHQ/sdk-proxy#12]
Hello, I've been having an issue with the SDK proxy, specifically when using the UDP sockets with the command. I've attached a PR that adds a couple example applications with docker-compose files for easy setup. The HTTP hello world app works with through both the web server through the browser and the CLI. The UDP hello world app works through just the CLI, but fails through the web server/browser. 

Here is the PR: https://github.com/DevCycleHQ/php-server-sdk/pull/62

This setup is meant to imitate the setup our company has with AWS Elastic Beanstalk. We're trying hard to get the UDP socket functionality working. We have a PR internally for getting the proxy setup with just HTTP, but we're reviewing if we find that acceptable for our use-case. 
When spinning up the containers locally, don't forget to put a valid DevCycle key in the Dockerfile and docker-compose.yml.
The command I'm running to test functionality through the CLI is `docker-compose exec app php variable.php`

**Comment by JamieSinn** [comment]
From further investigation - it seems like this is related to the file permissions in the default setup of `net.Listen` being 755; the easy fix is to change the permissions to the socket file to be 777 after creation; but given this is not a standard deployment recommendation, the default operation shouldn't change.

As an easy option for this #13 should be able to create a more friendly and less "why isn't this working" question on startup.
